FROM opensearchproject/opensearch-dashboards:2.19.3
RUN /usr/share/opensearch-dashboards/bin/opensearch-dashboards-plugin remove securityDashboards
RUN /usr/share/opensearch-dashboards/bin/opensearch-dashboards-plugin remove flowFrameworkDashboards
RUN /usr/share/opensearch-dashboards/bin/opensearch-dashboards-plugin remove mlCommonsDashboards
RUN /usr/share/opensearch-dashboards/bin/opensearch-dashboards-plugin remove queryInsightsDashboards
