name: Manual Random Tester E2E Azure

on:
  workflow_dispatch:
    inputs:
      flaky-specs-to-random-test:
        description: List of flaky specs to random test
        default: ""
        required: true
        type: string
      frontend-commit-sha:
        description: Optional frontend tag to override
        default: ""
        required: false
        type: string
      backend-commit-sha:
        description: Optional backend tag to override
        default: ""
        required: false
        type: string
      dump-type:
        description: If you override backend-commit-sha from a PR specifically, you MUST set this value to the word dev
        required: false
        type: string
        default: "master"

jobs:
  get-github-email:
    runs-on: micro-runner
    outputs:
      github-email: ${{ steps.get-email.outputs.email }}
    steps:
      - name: Get GitHub Email
        id: get-email
        run: |
          user_name="${{ github.actor }}"
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                          -H "Accept: application/vnd.github.v3+json" \
                          "https://api.github.com/users/$user_name")
          email=$(echo "$response" | jq -r '.email // empty')
          echo "email=$email" >> $GITHUB_OUTPUT

  echo-github-email:
    runs-on: micro-runner
    steps:
      - name: Echo GitHub Email
        run: |
          echo "${{ needs.get-github-email.outputs.github-email }}"
